apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kasalights.kvecchione.dev
spec:
  scope: Namespaced
  group: kvecchione.dev
  names:
    kind: KasaLight
    plural: kasalights
    singular: kasalight
    shortNames:
      - kl
      - kls
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ip:
                  type: string
                  format: ipv4
                state:
                  type: string
                  enum: 
                  - 'on'
                  - 'off'
                type:
                  type: string
                  enum: 
                  - plug
                  - bulb
