---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: kasa-lights-operator-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kasa-lights-operator-role-cluster
rules:
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [kvecchione.dev]
    resources: [kasalights]
    verbs: [list, watch, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kasa-lights-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kasa-lights-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: kasa-lights-operator-serviceaccount
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasa-lights-operator
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: kasa-lights-operator
  template:
    metadata:
      labels:
        application: kasa-lights-operator
    spec:
      serviceAccountName: kasa-lights-operator-serviceaccount
      containers:
      - name: kasa-lights-operator
        image: ghcr.io/kvecchione/kasa-lights-operator:latest